### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Windows87** [Windows87/presencial-black#1]
- [ ] Corrigir cores do texto (label, div, select)
- [ ] Cores quando ocorre o :hover
- [ ] Colocar no Chrome Extensions
- [ ] Tradução em Inglês
